insert into registrados (nome_registrado, RA) values ("BIANCA SOARES DE OLIVEIRA","6996");
insert into registrados (nome_registrado, RA) values ("CLARA ADRIELI SOUZA OLIVEIRA","1741");
insert into registrados (nome_registrado, RA) values ("ERIK LUCAS DE ANDRADE SILVA","8448");
insert into registrados (nome_registrado, RA) values ("EYSHILA EUARY ANTUNES MARTINS FERREIRA LEITE","3691");
insert into registrados (nome_registrado, RA) values ("GABRIEL BRAGA NUNES","7143");
insert into registrados (nome_registrado, RA) values ("GABRIEL DOS SANTOS JESUINO","16663");
insert into registrados (nome_registrado, RA) values ("GABRIEL GAMA DA SILVA","8350");
insert into registrados (nome_registrado, RA) values ("GUSTAVO HENRIQUE DA SILVANO SIQUEIRA SILVA","19507");
insert into registrados (nome_registrado, RA) values ("HENRIQUE ROCHA DO NASCIMENTO","30082");
insert into registrados (nome_registrado, RA) values ("ISABELLY APARECIDA FARIA CARVALHO","19254");
insert into registrados (nome_registrado, RA) values ("ISAQUE CRUZ DE SIQUEIRA","13705");
insert into registrados (nome_registrado, RA) values ("JULIA RIBEIRO DO PRADO","12921");
insert into registrados (nome_registrado, RA) values ("KAIQUE FERREIRA TORRES","8078");
insert into registrados (nome_registrado, RA) values ("KAUANY GABRIELY MARQUES ADELINO","1928");
insert into registrados (nome_registrado, RA) values ("KEVYN DA CRUZ MARIANO","17830");
insert into registrados (nome_registrado, RA) values ("LAVINIA SILVA BARBOSA","1521");
insert into registrados (nome_registrado, RA) values ("LUAN HENRIQUE DOMINGOS DE SOUZA","10476");
insert into registrados (nome_registrado, RA) values ("MARIA VITORIA DE SOUZA RAMOS","3115");
insert into registrados (nome_registrado, RA) values ("MILLENA OLIVEIRA","11183");
insert into registrados (nome_registrado, RA) values ("MYGUEL KAUAN DOS SANTOS","12596");
insert into registrados (nome_registrado, RA) values ("NATHALY CAMILLY TOLEDO SILVA","14068");
insert into registrados (nome_registrado, RA) values ("NICOLAS SILVA","17917");
insert into registrados (nome_registrado, RA) values ("RAIANE SANTOS MATOS DE JESUS","4609");
insert into registrados (nome_registrado, RA) values ("RYAN DE JESUS OLIVEIRA DOS SANTOS","4086");
insert into registrados (nome_registrado, RA) values ("VICTOR RANGEL ALEXANDRO DE SOUZA SILVA","16376");
insert into registrados (nome_registrado, RA) values ("YASMIN MARCELLA RODRIGUES MACHADO","3244");
insert into registrados (nome_registrado, RA) values ("YOSSEF SILVA","11108");
insert into registrados (nome_registrado, RA) values ("Joyce Rocha Lima","40715");
insert into registrados (nome_registrado, RA) values ("BRENO HONORATO DOS SANTOS","33662");
insert into registrados (nome_registrado, RA) values ("ALLAN ANTHONY DE ANDRADE SOUSA","7406");
insert into registrados (nome_registrado, RA) values ("ANTONELLA PIETRA NEVES DE AZEVEDO","2614");
insert into registrados (nome_registrado, RA) values ("ARTHUR MARTINS RODRIGUES","4693");
insert into registrados (nome_registrado, RA) values ("DAVI MIGUEL LOURENÇO DE OLIVEIRA","18430");
insert into registrados (nome_registrado, RA) values ("EMANUELLY RAMOS ANDRADE MARQUES","1083");
insert into registrados (nome_registrado, RA) values ("ENZO DA SILVA SOUZA","9465");
insert into registrados (nome_registrado, RA) values ("ISABELLY VICTORIA DA SILVA","2199");
insert into registrados (nome_registrado, RA) values ("JASMIM AGATHA SOUSA SILVA","10483");
insert into registrados (nome_registrado, RA) values ("JHONATA FILIPE DA SILVA","15125");
insert into registrados (nome_registrado, RA) values ("JULIA DA CRUZ BIANCHIN","10203");
insert into registrados (nome_registrado, RA) values ("LARISSA DE MORAES NOGUEIRA","3027");
insert into registrados (nome_registrado, RA) values ("LAVINIA GABRIELLY RODRIGUES DE FREITAS","948");
insert into registrados (nome_registrado, RA) values ("LIVIA MAGALHAES DOS SANTOS","11944");
insert into registrados (nome_registrado, RA) values ("LUIS GABRIEL PAULINO RIBEIRO","16869");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA BARCELOS DUARTE","15234");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA PALMAGNANI RECH","10625");
insert into registrados (nome_registrado, RA) values ("NIKOLLAS HENRIQUE DA SILVA SOUSA","7527");
insert into registrados (nome_registrado, RA) values ("PEDRO ARTHUR DIAS DE OLIVEIRA","22598");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE DE SOUZA","8995");
insert into registrados (nome_registrado, RA) values ("RAFAELLI CAROLINA DE OLIVEIRA","12623");
insert into registrados (nome_registrado, RA) values ("RHYAN GABRIEL DOS SANTOS","7315");
insert into registrados (nome_registrado, RA) values ("SOPHIA MANUELLI TOLEDO DE FRANCA PERES","16686");
insert into registrados (nome_registrado, RA) values ("VITOR GOMES DE OLIVEIRA","5651");
insert into registrados (nome_registrado, RA) values ("VITOR MIGUEL DE SOUSA GERALDO","18789");
insert into registrados (nome_registrado, RA) values ("ANA LUISA MENDES RAMOS","11004");
insert into registrados (nome_registrado, RA) values ("YASMIM FERNANDA BARBOSA SOARES","38348");
insert into registrados (nome_registrado, RA) values ("ARTHUR BRUZZON DE SOUZA ROZA","16476");
insert into registrados (nome_registrado, RA) values ("CAIO DE CAMARGO SILVA","19120");
insert into registrados (nome_registrado, RA) values ("ENZO FELIPE MARIANO DOS SANTOS","1219");
insert into registrados (nome_registrado, RA) values ("HENZO GABRIEL BRUM ANDRAUS","5259");
insert into registrados (nome_registrado, RA) values ("ISADORA DOS SANTOS AMARAL","7149");
insert into registrados (nome_registrado, RA) values ("JOANA DOS SANTOS RODRIGUES","12384");
insert into registrados (nome_registrado, RA) values ("JOHN VICTOR CLEMENTINO DA SILVA","2120");
insert into registrados (nome_registrado, RA) values ("KAMILLY MARTINEZ CHOU","13177");
insert into registrados (nome_registrado, RA) values ("KAUAN DOS SANTOS NOGUEIRA","8570");
insert into registrados (nome_registrado, RA) values ("KAYQUE DA SILVA SANTOS","5445");
insert into registrados (nome_registrado, RA) values ("LUCAS PIRES BOARO","6361");
insert into registrados (nome_registrado, RA) values ("LUIZA CICONE RIBEIRO","10987");
insert into registrados (nome_registrado, RA) values ("MANUELA MARTINS DE FARIA","5880");
insert into registrados (nome_registrado, RA) values ("MARIA LUIZA INACIO CORREIA","6721");
insert into registrados (nome_registrado, RA) values ("MARIA VITÓRIA RODRIGUES PAJOY","39611");
insert into registrados (nome_registrado, RA) values ("MATHEUS RAPHAEL DE AQUINO PINTO","17136");
insert into registrados (nome_registrado, RA) values ("MIGUEL AUGUSTO DA SILVA PRADO","19436");
insert into registrados (nome_registrado, RA) values ("Miguel Reis de Azevedo","34375");
insert into registrados (nome_registrado, RA) values ("ROBSON GABRIEL LAVRA MORAIS","19496");
insert into registrados (nome_registrado, RA) values ("YASMIN VICTORIA DOS SANTOS SILVA","265");
insert into registrados (nome_registrado, RA) values ("MARIA JÚLIA DO CARMO MORAIS","40157");
insert into registrados (nome_registrado, RA) values ("ARTHUR CALHEIROS ALVES","40560");
insert into registrados (nome_registrado, RA) values ("JOÃO GABRIEL CASTELARI BARRERA","14316");
insert into registrados (nome_registrado, RA) values ("NICOLE CRISTINE DE MOURA PRADO","17900");
insert into registrados (nome_registrado, RA) values ("ALLANA VITORIA DE MELO MOREIRA","1430");
insert into registrados (nome_registrado, RA) values ("ANA CAROLINA SANTOS SILVA","35435");
insert into registrados (nome_registrado, RA) values ("ANA CLARA DA SILVA FERREIRA","11339");
insert into registrados (nome_registrado, RA) values ("ANANDRA GABRIELE EUGENIA CABRAL","13020");
insert into registrados (nome_registrado, RA) values ("ARTHUR VINICIUS DA SILVA","4085");
insert into registrados (nome_registrado, RA) values ("CAUA RIBEIRO ROMERO","11013");
insert into registrados (nome_registrado, RA) values ("ERON DO PRADO FELIS","40119");
insert into registrados (nome_registrado, RA) values ("GIOVANNA MYKAELA GENOVEZ","8561");
insert into registrados (nome_registrado, RA) values ("ISABEL CRISTINA DE ALMEIDA AGUIAR LIMA","22599");
insert into registrados (nome_registrado, RA) values ("ISABELLY SAYURI DE ALMEIDA","14113");
insert into registrados (nome_registrado, RA) values ("JOAO LUCAS SOARES AFONSO","18227");
insert into registrados (nome_registrado, RA) values ("KEYO LUCCA GARIBALDI VIEIRA","26183");
insert into registrados (nome_registrado, RA) values ("LETICIA ALEXANDRA DIAS DA SILVEIRA","17767");
insert into registrados (nome_registrado, RA) values ("LUAN HENRIQUE DIAS DE CARVALHO","7589");
insert into registrados (nome_registrado, RA) values ("MAURICIO AUGUSTO NILO CRISPIM","8224");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE TEODORO FERNANDES","15545");
insert into registrados (nome_registrado, RA) values ("RAFAEL HENRIQUE MANELLI FARIAS","15189");
insert into registrados (nome_registrado, RA) values ("REBECA GUIMARAES MARTINS","12787");
insert into registrados (nome_registrado, RA) values ("RENATO GABRIEL SANTOS RODRIGUES","17216");
insert into registrados (nome_registrado, RA) values ("RYAN DOS SANTOS FERREIRA","17149");
insert into registrados (nome_registrado, RA) values ("RYAN POLICARPO DE ARAUJO SILVA","12258");
insert into registrados (nome_registrado, RA) values ("SAMUEL REIS BUSTAMANTE DE JESUS","6752");
insert into registrados (nome_registrado, RA) values ("VINICIUS DE SOUSA SILVA","13007");
insert into registrados (nome_registrado, RA) values ("MIGUEL DE FREITAS CHAVES","1696");
insert into registrados (nome_registrado, RA) values ("ANA LIVIA ALVES CABRAL","1861");
insert into registrados (nome_registrado, RA) values ("ANNA LAURA DE MEDEIROS PASSOS","3580");
insert into registrados (nome_registrado, RA) values ("ANTONIO FELIPE DIAS DA SILVEIRA","18879");
insert into registrados (nome_registrado, RA) values ("ENZO GABRIEL DA SILVA","11483");
insert into registrados (nome_registrado, RA) values ("FELIPE GABRIEL SANTOS PINA","17231");
insert into registrados (nome_registrado, RA) values ("ISAC SANTOS","35008");
insert into registrados (nome_registrado, RA) values ("JOAO VITOR FONSECA CAMPOS","18560");
insert into registrados (nome_registrado, RA) values ("KEVEN BLAYAN APARECIDO SANTOS MENDES","7990");
insert into registrados (nome_registrado, RA) values ("LEANDRO JOSE DE ALMEIDA RIBEIRO","1063");
insert into registrados (nome_registrado, RA) values ("LIVIA DE OLIVEIRA CARVALHO","19117");
insert into registrados (nome_registrado, RA) values ("LUAN DE PAULA SANTOS","27143");
insert into registrados (nome_registrado, RA) values ("LUAN HENRIQUE COSTA DA SILVA","17658");
insert into registrados (nome_registrado, RA) values ("LUCAS SANTOS DE SOUZA","39660");
insert into registrados (nome_registrado, RA) values ("MANUELA SOARES PEREIRA DE AQUINO","2518");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA GONÇALVES MARCHIONE RIBEIRO","19563");
insert into registrados (nome_registrado, RA) values ("MARIA LUIZA DA SILVA BASTOS","6396");
insert into registrados (nome_registrado, RA) values ("MARIA VITORIA DE JESUS SILVA","23183");
insert into registrados (nome_registrado, RA) values ("MILLENY DUARTE FINETTI","19395");
insert into registrados (nome_registrado, RA) values ("PYETRO MIGUEL ALVES DOS SANTOS REZENDE","4546");
insert into registrados (nome_registrado, RA) values ("RAFAELA APARECIDA CAMPOS","8868");
insert into registrados (nome_registrado, RA) values ("RAPHAEL HENRIQUE MENDONÇA DE PAULA RAMOS","23245");
insert into registrados (nome_registrado, RA) values ("RICHARD MATHEUS GONCALVES DOS SANTOS","10712");
insert into registrados (nome_registrado, RA) values ("TAINA DE OLIVEIRA ANDRADE","15358");
insert into registrados (nome_registrado, RA) values ("RAÍ DAVIDSON ASSUNÇÃO","40167");
insert into registrados (nome_registrado, RA) values ("GABRIEL DE FREITAS CHAVES","8783");
insert into registrados (nome_registrado, RA) values ("ISABELLY LUIZA RIBEIRO DOS SANTOS FERNANDES","40561");
insert into registrados (nome_registrado, RA) values ("GUSTAVO SOARES BARROS DA SILVA","41205");
insert into registrados (nome_registrado, RA) values ("ALEFF CORREA MENDES","14114");
insert into registrados (nome_registrado, RA) values ("ALIC DAVI COUTINHO NUNES","12724");
insert into registrados (nome_registrado, RA) values ("BIANCA CRISTINA LUCHETTI DOS SANTOS","3846");
insert into registrados (nome_registrado, RA) values ("CAUA NUNES DE BRITO","6791");
insert into registrados (nome_registrado, RA) values ("DAVI PAIVA FURTUOSO","13339");
insert into registrados (nome_registrado, RA) values ("DAYANE DE JESUS SANTOS","1751");
insert into registrados (nome_registrado, RA) values ("DERICK ALVES CANDIDO DA SILVA","1447");
insert into registrados (nome_registrado, RA) values ("EMELLYN CRISTINE SILVA DE MORAES","13373");
insert into registrados (nome_registrado, RA) values ("ENZO BARBOSA MOREIRA SOUZA","9047");
insert into registrados (nome_registrado, RA) values ("GABRIEL DAVI RAMOS DOS SANTOS","27053");
insert into registrados (nome_registrado, RA) values ("GUSTAVO ADAMO DE MELO","209");
insert into registrados (nome_registrado, RA) values ("ITAMAR SILVA SANTOS","16109");
insert into registrados (nome_registrado, RA) values ("JENIFFER LUIZA TANJONI RODRIGUES","10779");
insert into registrados (nome_registrado, RA) values ("JOÃO VITOR DAS NEVES SILVA","36249");
insert into registrados (nome_registrado, RA) values ("JOAO VITOR NOBREGA DA SILVA","11630");
insert into registrados (nome_registrado, RA) values ("KAUA DA SILVA SANTOS","5331");
insert into registrados (nome_registrado, RA) values ("KAUAN VINYCIUS LEMES RODRIGUES","13993");
insert into registrados (nome_registrado, RA) values ("MAIRA TAVARES MOREIRA DA SILVA","799");
insert into registrados (nome_registrado, RA) values ("MANUELA FRANCO BARRIOS","17488");
insert into registrados (nome_registrado, RA) values ("MARIA HELOIZA DAVID SANTOS","18955");
insert into registrados (nome_registrado, RA) values ("MELISSA RAMOS MIRANDA DOS PASSOS","18585");
insert into registrados (nome_registrado, RA) values ("MIGUEL ANTONIO FERNANDES SANTOS","190");
insert into registrados (nome_registrado, RA) values ("MIGUEL HENRIQUE DOS SANTOS ZAMBRIM","5987");
insert into registrados (nome_registrado, RA) values ("MIKAELLA EMILLY GARCIA","17501");
insert into registrados (nome_registrado, RA) values ("REBEKA ALVES DOS SANTOS","34146");
insert into registrados (nome_registrado, RA) values ("ROBERT SOUZA DA FE","5714");
insert into registrados (nome_registrado, RA) values ("VITÓRIA GABRIELLY FERREIRA OLIVEIRA RODRIGUES","38976");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE ANDRE DOS SANTOS","8469");
insert into registrados (nome_registrado, RA) values ("EDSON DAVID ALCANTARA NOVAIS","13558");
insert into registrados (nome_registrado, RA) values ("MIRELLA DE SOUZA PEREIRA","4408");
insert into registrados (nome_registrado, RA) values ("ALICE MANCILHA CARVALHO","12610");
insert into registrados (nome_registrado, RA) values ("ANNA LUIZA LOURENCO COSTA","2775");
insert into registrados (nome_registrado, RA) values ("DÉRIK DE OLIVEIRA CECCI","28238");
insert into registrados (nome_registrado, RA) values ("ISABELLA LOPES DE OLIVEIRA GONÇALVES","21265");
insert into registrados (nome_registrado, RA) values ("JOÃO PEDRO DA SILVA COSTA","17685");
insert into registrados (nome_registrado, RA) values ("JOSÉ ANTONIO DE VENÂNCIO NICOLAU","17506");
insert into registrados (nome_registrado, RA) values ("LAURA GOMES CARVALHO","20554");
insert into registrados (nome_registrado, RA) values ("LIVIA CANDIA QUEIROZ DE BRITO","26301");
insert into registrados (nome_registrado, RA) values ("LUCAS RENAN BICUDO DOS SANTOS","24082");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA ALMEIDA SANTOS","19166");
insert into registrados (nome_registrado, RA) values ("PATRICIA VICTHÓRIA ALCANTARA NOVAIS","9086");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE REIS DOS SANTOS","23686");
insert into registrados (nome_registrado, RA) values ("PEDRO MIGUEL CANDIDO DE MELO","8058");
insert into registrados (nome_registrado, RA) values ("RAONNY HENRIQUE TOLEDO SILVA","1887");
insert into registrados (nome_registrado, RA) values ("RHAILANDER DIAS DA SILVA","31108");
insert into registrados (nome_registrado, RA) values ("ROMULO LUCHETTI RIBEIRO","660");
insert into registrados (nome_registrado, RA) values ("SARA CRISTYNA RODRIGUES DIAS","21484");
insert into registrados (nome_registrado, RA) values ("SOFIA DA MOTA ROCHA","30453");
insert into registrados (nome_registrado, RA) values ("SOPHIA SOUSA FERREIRA","9388");
insert into registrados (nome_registrado, RA) values ("VICTOR GABRIEL BARBOSA DE JESUS","23933");
insert into registrados (nome_registrado, RA) values ("VICTÓRIA DE LOURDES GOMES FARIA","23934");
insert into registrados (nome_registrado, RA) values ("VICTÓRIA EMANUELLY DIOGO","5700");
insert into registrados (nome_registrado, RA) values ("YASMIN SILVA DE OLIVEIRA","11113");
insert into registrados (nome_registrado, RA) values ("MARIA GABRIELA DE FÁTIMA MORAIS","40156");
insert into registrados (nome_registrado, RA) values ("Emanuelly Vitoria de Souza Anacleto","19855");
insert into registrados (nome_registrado, RA) values ("DAVI LUCCA DOS SANTOS","37355");
insert into registrados (nome_registrado, RA) values ("EMILLY CRISTINE SILVA","21937");
insert into registrados (nome_registrado, RA) values ("FRANCIELLY EMILLY CANDIA DO NASCIMENTO","23421");
insert into registrados (nome_registrado, RA) values ("ANA BEATRIZ LEVAK DA SILVA","12389");
insert into registrados (nome_registrado, RA) values ("ANA CLARA FONSECA MOREIRA","22494");
insert into registrados (nome_registrado, RA) values ("ANA LUIZA RODRIGUES DE MATOS","22596");
insert into registrados (nome_registrado, RA) values ("ANTONELLA GARIBALDI SILVA","22499");
insert into registrados (nome_registrado, RA) values ("CLÁUDIO CALHEIROS DA SILVEIRA JÚNIOR","22497");
insert into registrados (nome_registrado, RA) values ("CRYSTAL MAYARA BUSTAMANTE DE JESUS","14001");
insert into registrados (nome_registrado, RA) values ("ENZO JOAQUIM ALVES SIQUEIRA EXPEDITO","28138");
insert into registrados (nome_registrado, RA) values ("FRANCESCO PIO DOS SANTOS RIBEIRO BERTOLOTTI","28248");
insert into registrados (nome_registrado, RA) values ("GRENDHA GEOVANNA MONTUANI MOREIRA","28390");
insert into registrados (nome_registrado, RA) values ("ISABELLA THAEME CASSIANO DA SILVA","16948");
insert into registrados (nome_registrado, RA) values ("JADE DE JESUS GOMES DE ALMEIDA","22592");
insert into registrados (nome_registrado, RA) values ("JOÃO MIGUEL FERREIRA LEITE","9389");
insert into registrados (nome_registrado, RA) values ("JONAS BERNARDO DE MATOS ARAUJO","19393");
insert into registrados (nome_registrado, RA) values ("KAWÃ HENRIQUE FERNANDES SENA","22593");
insert into registrados (nome_registrado, RA) values ("KETELLYN EDUARDA ARANTES AMARAL","202");
insert into registrados (nome_registrado, RA) values ("LETHICIA PATRICIO DE FREITAS","4223");
insert into registrados (nome_registrado, RA) values ("MANUELLA LEAH SANTOS","20827");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA DOS SANTOS JESUÍNO","28265");
insert into registrados (nome_registrado, RA) values ("MARIA ISABEL DIAS DA SILVEIRA","18104");
insert into registrados (nome_registrado, RA) values ("MARIA JÚLIA DE JESUS GOMES DE ALMEIDA","22594");
insert into registrados (nome_registrado, RA) values ("MIGUEL WENDELL DA SILVA SANTOS","12282");
insert into registrados (nome_registrado, RA) values ("MILENA VITORIA DE ALMEIDA DANIEL RIBEIRO","5641");
insert into registrados (nome_registrado, RA) values ("NICOLAS RAFAEL OLIVEIRA TIRADO","1995");
insert into registrados (nome_registrado, RA) values ("NICOLE SILVA","22597");
insert into registrados (nome_registrado, RA) values ("PABLO WELLINGTON SANTOS DA SILVA","35436");
insert into registrados (nome_registrado, RA) values ("RAFAELA CARVALHO RAMOS SILVA","10972");
insert into registrados (nome_registrado, RA) values ("RAFAELLA FULGENCIO DOS SANTOS","6845");
insert into registrados (nome_registrado, RA) values ("RILLARY GABRIELI TINOCO PIMENTEL","18680");
insert into registrados (nome_registrado, RA) values ("RAFAEL ANTONIO GONCALVES MARTINS SOARES","20960");
insert into registrados (nome_registrado, RA) values ("ANNA CLARA DOS SANTOS SILVA","20925");
insert into registrados (nome_registrado, RA) values ("ANNY CATHARINY BARBOSA DE ARAUJO","23278");
insert into registrados (nome_registrado, RA) values ("DANILO CONEJO FARIA DE OLIVEIRA","4420");
insert into registrados (nome_registrado, RA) values ("DAVI LUCCA FERNANDES BARBOSA","25869");
insert into registrados (nome_registrado, RA) values ("DAVI OLIVEIRA MELO","30193");
insert into registrados (nome_registrado, RA) values ("DAVID DE OLIVEIRA CECCI","30224");
insert into registrados (nome_registrado, RA) values ("ERICK HENRIQUE MOREIRA DA SILVA","20669");
insert into registrados (nome_registrado, RA) values ("FELIPE MIGUEL FARIA DE SOUZA","23551");
insert into registrados (nome_registrado, RA) values ("GABRIELLY PAULISTA FARIA DE OLIVEIRA","2635");
insert into registrados (nome_registrado, RA) values ("ISADORA SOFIA RODRIGUES WURMEISTER","10507");
insert into registrados (nome_registrado, RA) values ("JONATHAN WILLIAN TANJONI RODRIGUES","30201");
insert into registrados (nome_registrado, RA) values ("LARISSA PEREIRA DA SILVA","18661");
insert into registrados (nome_registrado, RA) values ("LAUREN SOPHIA DE SÁ MESSIAS BARBEDO","20445");
insert into registrados (nome_registrado, RA) values ("MARIA CECÍLIA ROCHA GONCALVES","26262");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA SANT ANNA","6380");
insert into registrados (nome_registrado, RA) values ("MARIA JULIA VALENTIM GENOVEZ","28349");
insert into registrados (nome_registrado, RA) values ("MIGUEL DIORGE DE OLIVEIRA MARINS","30216");
insert into registrados (nome_registrado, RA) values ("MIGUEL DOS SANTOS ESPINA","5137");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE SOUZA MARTINS","30220");
insert into registrados (nome_registrado, RA) values ("RAPHAELA SILVA BORGES","24029");
insert into registrados (nome_registrado, RA) values ("RYAN VINICIUS FARIA NASCIMENTO","30221");
insert into registrados (nome_registrado, RA) values ("SOPHIA FERNANDA GOMES PIMENTEL","7631");
insert into registrados (nome_registrado, RA) values ("WALLACE NATAN FERREIRA MARÇAL","38977");
insert into registrados (nome_registrado, RA) values ("THAYNARA CAMARGO GONÇALVES","31406");
insert into registrados (nome_registrado, RA) values ("ARTHUR DE LIMA DOS SANTOS","1245");
insert into registrados (nome_registrado, RA) values ("ABNER MORAES DOS SANTOS RAMOS","252");
insert into registrados (nome_registrado, RA) values ("AERON ESTEVES DE ARAÚJO","34944");
insert into registrados (nome_registrado, RA) values ("ANNA BEATRIZ CARVALHO DIAS","34935");
insert into registrados (nome_registrado, RA) values ("ANTHONY MIGUEL DE ALMEIDA CASANOVA","23992");
insert into registrados (nome_registrado, RA) values ("BIANCA APARECIDA DA SILVA PEREIRA","30187");
insert into registrados (nome_registrado, RA) values ("BRAYAN NOVAIS DE PAULA","1497");
insert into registrados (nome_registrado, RA) values ("BRYAN FERREIRA DA SILVA","31733");
insert into registrados (nome_registrado, RA) values ("DAVI HENRIQUE ROCHA SILVA","20693");
insert into registrados (nome_registrado, RA) values ("EMILLY VITÓRIA DA SILVA FURTUOSO","30382");
insert into registrados (nome_registrado, RA) values ("GUSTAVO PEREIRA MARIA","11187");
insert into registrados (nome_registrado, RA) values ("ISABELLY RAFAELLA DA SILVA BARBOSA","30197");
insert into registrados (nome_registrado, RA) values ("JOÃO MIGUEL TAVARES MOREIRA DA SILVA","30683");
insert into registrados (nome_registrado, RA) values ("JOÃO PEDRO DE MELO","6368");
insert into registrados (nome_registrado, RA) values ("KAUAN HENRIQUE LOPES DE JESUS","31947");
insert into registrados (nome_registrado, RA) values ("KAUANNY GOMES FARIA DA SILVA","25515");
insert into registrados (nome_registrado, RA) values ("LEVI NAZARIO RAMOS","34598");
insert into registrados (nome_registrado, RA) values ("LIVIA CHRISTINA PETRUCCI FERNANDES","25770");
insert into registrados (nome_registrado, RA) values ("LUÍS GUSTAVO DE SOUZA SANTOS","34957");
insert into registrados (nome_registrado, RA) values ("MIGUEL GONÇALVES ALVES DA SILVA","38662");
insert into registrados (nome_registrado, RA) values ("SAMUEL ALBUQUERQUE DE CAMPOS","25707");
insert into registrados (nome_registrado, RA) values ("THIAGO HENRIQUE PAULISTA FARIA MONTEIRO","17886");
insert into registrados (nome_registrado, RA) values ("YAGO BASILIO DA SILVA SANTOS","35461");
insert into registrados (nome_registrado, RA) values ("GABRIEL LUGGERI DOS SANTOS","30675");
insert into registrados (nome_registrado, RA) values ("KEVEN WILLIAN COSTA XAVIER DA SILVA","23477");
insert into registrados (nome_registrado, RA) values ("ADRYNA LAIS DA SILVA SIQUEIRA","30229");
insert into registrados (nome_registrado, RA) values ("ALICE DE OLIVEIRA MACHADO","8987");
insert into registrados (nome_registrado, RA) values ("ANA JULIA LIMA VASQUES","12891");
insert into registrados (nome_registrado, RA) values ("ANA LUIZA CAMILO SOUZA","30642");
insert into registrados (nome_registrado, RA) values ("EMANUELLY GOMES AMORIM","15319");
insert into registrados (nome_registrado, RA) values ("ENZO HENRIQUE DOS SANTOS","30236");
insert into registrados (nome_registrado, RA) values ("HECTOR HUGO LIMA DE OLIVEIRA","24129");
insert into registrados (nome_registrado, RA) values ("ISABELLA VITÓRIA CORDEIRO MAIA","31723");
insert into registrados (nome_registrado, RA) values ("JOÃO LUCAS SOUZA LOPES DE OLIVEIRA","30242");
insert into registrados (nome_registrado, RA) values ("JOÃO MIGUEL DOS SANTOS","29409");
insert into registrados (nome_registrado, RA) values ("JOAO RAMOS DA SILVA NETO","10854");
insert into registrados (nome_registrado, RA) values ("JOÃO VICTOR FERNANDES ABREU","12296");
insert into registrados (nome_registrado, RA) values ("KAUANY MARTINS NERY","30268");
insert into registrados (nome_registrado, RA) values ("KAUÊ GABRIEL MIRANDA PIRES","23330");
insert into registrados (nome_registrado, RA) values ("LUCAS GABRIEL DE SOUSA NASCIMENTO","37032");
insert into registrados (nome_registrado, RA) values ("LUCAS JOSÉ DE LIMA","30276");
insert into registrados (nome_registrado, RA) values ("MARIANA BLOIS RAMOS DOS SANTOS","24019");
insert into registrados (nome_registrado, RA) values ("MATHEUS FELIPE SANTOS CORREIA","39552");
insert into registrados (nome_registrado, RA) values ("MELISSA ALVES RODRIGUES DE PAULA","30285");
insert into registrados (nome_registrado, RA) values ("MELISSA DOS SANTOS LEITE","23618");
insert into registrados (nome_registrado, RA) values ("PEDRO MIGUEL DOMINGOS SANTOS SOARES","30292");
insert into registrados (nome_registrado, RA) values ("RENAN APARECIDO SOUZA ALBUQUERQUE","30297");
insert into registrados (nome_registrado, RA) values ("THAYRON APARECIDO SANTOS MENDES","30384");
insert into registrados (nome_registrado, RA) values ("VICTOR KAIKE DE SOUZA RODRIGUES","30727");
insert into registrados (nome_registrado, RA) values ("ANGELO GABRIEL TEIXEIRA RENTE","40566");
insert into registrados (nome_registrado, RA) values ("ANA BEATRIZ SOARES BARROS DA SILVA","41206");
insert into registrados (nome_registrado, RA) values ("AGHATA RODRIGUES DE CAMPOS ROSA","29352");
insert into registrados (nome_registrado, RA) values ("ANA BEATRIZ SOUZA DA CUNHA","20262");
insert into registrados (nome_registrado, RA) values ("ANA CLARA CAMILO SOUZA","30636");
insert into registrados (nome_registrado, RA) values ("ANA LUIZA PAULA DA SILVA","25819");
insert into registrados (nome_registrado, RA) values ("BEATRIZ VICTOR MOTA","19900");
insert into registrados (nome_registrado, RA) values ("BRAYON MYCKAELL DA SILVA TEIXEIRA","7526");
insert into registrados (nome_registrado, RA) values ("BRIAN GARCIA DE CARVALHO","34952");
insert into registrados (nome_registrado, RA) values ("ENZO RODRIGUES CORRÊA","30657");
insert into registrados (nome_registrado, RA) values ("GABRIELLY VITÓRIA RIBEIRO DE ANDRADE","29167");
insert into registrados (nome_registrado, RA) values ("ISAQUE HENRIQUE DA SILVA CANDIDO","21804");
insert into registrados (nome_registrado, RA) values ("KAUÃ HENRIQUE BAPTISTA DA SILVA","7718");
insert into registrados (nome_registrado, RA) values ("LARA VITORIA DA SILVA","25879");
insert into registrados (nome_registrado, RA) values ("LAZZARO LOHAN SOARES SILVA","27762");
insert into registrados (nome_registrado, RA) values ("LETICIA GABRIELLY DOS SANTOS JESUÍNO","30707");
insert into registrados (nome_registrado, RA) values ("MURILO DE ALMEIDA DOS SANTOS","23616");
insert into registrados (nome_registrado, RA) values ("REBECA CARDOSO RABELO DAS GRAÇAS","30720");
insert into registrados (nome_registrado, RA) values ("REBECA DE JESUS SANTOS","5322");
insert into registrados (nome_registrado, RA) values ("SOFIA VITORIA MEDEIROS DOS SANTOS","1103");
insert into registrados (nome_registrado, RA) values ("TAISA KAMILY SALDANHA VIANA","4724");
insert into registrados (nome_registrado, RA) values ("WALLYSSON DOUGLAS MONTEIRO DOS REIS","33729");
insert into registrados (nome_registrado, RA) values ("ANA LUIZA CAMILO SOUZA","30642");
insert into registrados (nome_registrado, RA) values ("FELIPE MIGUEL FARIA DE SOUZA","23551");
insert into registrados (nome_registrado, RA) values ("ISABELLY RAFAELLA DA SILVA BARBOSA","30197");
insert into registrados (nome_registrado, RA) values ("GUSTAVO PEREIRA MARIA","11187");
insert into registrados (nome_registrado, RA) values ("GUILHERME HENRIQUE DA SILVA SILVANO","41257");
insert into registrados (nome_registrado, RA) values ("ÁLEF EMANUEL NORONHA GUIMARÃES","22590");
insert into registrados (nome_registrado, RA) values ("ANA BEATRIZ PAULA REIS","21611");
insert into registrados (nome_registrado, RA) values ("ARTHUR MIGUEL DUARTE DE BRITO","6115");
insert into registrados (nome_registrado, RA) values ("BIANCA RODRIGUES GOMES PAULINO","23590");
insert into registrados (nome_registrado, RA) values ("CASSIO DA SILVA CAMPOS","18383");
insert into registrados (nome_registrado, RA) values ("DAVI MATHEUS DE SOUZA MARQUES BERTES DOS SANTOS","14006");
insert into registrados (nome_registrado, RA) values ("EDUARDO MIRANDA BORTOLON","6064");
insert into registrados (nome_registrado, RA) values ("EMILLY BEATRIZ DA SILVA FINETTI","25739");
insert into registrados (nome_registrado, RA) values ("GUILHERME DA SILVA SOUZA","22844");
insert into registrados (nome_registrado, RA) values ("KAYO OLIVEIRA DE CARVALHO","37571");
insert into registrados (nome_registrado, RA) values ("LUCAS HENRIQUE GOMES DE FRANCA","2257");
insert into registrados (nome_registrado, RA) values ("LUCAS MOURA DE ARAUJO SANTOS","4922");
insert into registrados (nome_registrado, RA) values ("LUCAS REZENDE DE OLIVEIRA","22498");
insert into registrados (nome_registrado, RA) values ("LUIZ HENRIQUE QUEIROZ AMARAL","12860");
insert into registrados (nome_registrado, RA) values ("MAIARA DOS SANTOS MOREIRA","16969");
insert into registrados (nome_registrado, RA) values ("MAIHELE TAVARES MOREIRA DA SILVA","22495");
insert into registrados (nome_registrado, RA) values ("MATTEUS KAICK BRAZ DE FARIA","15037");
insert into registrados (nome_registrado, RA) values ("NICOLAS MÁXIMO DUARTE","27144");
insert into registrados (nome_registrado, RA) values ("RAFAEL ANTONIO GONCALVES MARTINS SOARES","20960");
insert into registrados (nome_registrado, RA) values ("RAFAEL FRANCO BUENO","2510");
insert into registrados (nome_registrado, RA) values ("REBECA GUIMARÃES ROCHA","22501");
insert into registrados (nome_registrado, RA) values ("RYAN GABRIEL CYRIO SANTOS","7189");
insert into registrados (nome_registrado, RA) values ("SARA LORRANE CRUZ DOS REIS","19493");
insert into registrados (nome_registrado, RA) values ("SOPHIA VITORIA DA SILVA LUSTOSA","17583");
insert into registrados (nome_registrado, RA) values ("THIAGO VICENTE SARAIVA","8318");
insert into registrados (nome_registrado, RA) values ("VINICIUS ANDRADE OLIVEIRA","2181");
insert into registrados (nome_registrado, RA) values ("YASMIN DA SILVA CASSIANO","22500");
insert into registrados (nome_registrado, RA) values ("MIKAELE CHAVES DE CAMARGO","17483");
insert into registrados (nome_registrado, RA) values ("MARCOS MOURA DE SOUZA SILVA","1064");
insert into registrados (nome_registrado, RA) values ("VICTOR HUGO DA SILVA BASTOS","5421");
insert into registrados (nome_registrado, RA) values ("GABRIEL DA SILVA SOUSA","23614");
insert into registrados (nome_registrado, RA) values ("ANNA CLARA LAURINDO DA SILVA","635");
insert into registrados (nome_registrado, RA) values ("ANA LUISA MENDES RAMOS","11004");
insert into registrados (nome_registrado, RA) values ("CLARICE PELODAN DE MORAIS","5174");
insert into registrados (nome_registrado, RA) values ("DAVI OLIVEIRA SOUZA","15912");
insert into registrados (nome_registrado, RA) values ("GABRIEL VICENTE RODRIGUES","3154");
insert into registrados (nome_registrado, RA) values ("HADASSA GABRIELLY DOS SANTOS SILVA","38120");
insert into registrados (nome_registrado, RA) values ("JHONATA DE OLIVEIRA CARDOSO","3261");
insert into registrados (nome_registrado, RA) values ("JOÃO PEDRO MOREIRA SIMÃO DE ABREU","599");
insert into registrados (nome_registrado, RA) values ("KYARA DA SILVA RIBEIRO BATISTA","13430");
insert into registrados (nome_registrado, RA) values ("LEONARDO DE AQUINO COSTA","3493");
insert into registrados (nome_registrado, RA) values ("LIVIA MOREIRA CUNHA","17574");
insert into registrados (nome_registrado, RA) values ("LORRAYNE CAROLYNE COSTA PEREIRA","2594");
insert into registrados (nome_registrado, RA) values ("MAYTHE HELOUYSE DE SÁ MESSIAS BARBEDO","4290");
insert into registrados (nome_registrado, RA) values ("MIGUEL ALEXANDRE OLIVEIRA BEZERRA","23282");
insert into registrados (nome_registrado, RA) values ("MIGUEL DA SILVA BORGES","4792");
insert into registrados (nome_registrado, RA) values ("NAYARA CONEJO FARIA DE OLIVEIRA","17030");
insert into registrados (nome_registrado, RA) values ("PABLO MIGUEL PAULISTA FARIA MONTEIRO","3060");
insert into registrados (nome_registrado, RA) values ("PIETRO HENRIQUE VIDAL DINIZ","3018");
insert into registrados (nome_registrado, RA) values ("RAFAELA DA SILVA","30148");
insert into registrados (nome_registrado, RA) values ("TIFFANY XAVIER COSTA","5746");
insert into registrados (nome_registrado, RA) values ("YASMIN RAFAELA DOS REIS MANÇO","38685");
insert into registrados (nome_registrado, RA) values ("LORENZO GONÇALVES BONFIM","40405");
insert into registrados (nome_registrado, RA) values ("ANA LUISA MENDES RAMOS","11004");
insert into registrados (nome_registrado, RA) values ("PEDRO LUCAS MAZZINI DE OLIVEIRA","2262");
insert into registrados (nome_registrado, RA) values ("ALICE COUTINHO BARBOSA DOS SANTOS","16784");
insert into registrados (nome_registrado, RA) values ("BEATRIZ MIRANDA DO AMARAL","4821");
insert into registrados (nome_registrado, RA) values ("CESARY HENRIQUE KOENGKAN THEODORO","6838");
insert into registrados (nome_registrado, RA) values ("DIOGO OLIVEIRA ROSA","7354");
insert into registrados (nome_registrado, RA) values ("JOAO PEDRO DA SILVA IZIDORO","3567");
insert into registrados (nome_registrado, RA) values ("JOÃO ROBERTO SILVA SANTOS","15589");
insert into registrados (nome_registrado, RA) values ("JOÃO VICTOR DE CAMPOS LEITE CABRAL","11026");
insert into registrados (nome_registrado, RA) values ("JOHNATAN JULIO JOFRAN FIDELIS DA SILVA","5071");
insert into registrados (nome_registrado, RA) values ("JULIA MELO PEREIRA","4615");
insert into registrados (nome_registrado, RA) values ("KAUÃ SOUZA DE OLIVEIRA","7644");
insert into registrados (nome_registrado, RA) values ("KAYLLA HELENA FREITAS DINIZ","9125");
insert into registrados (nome_registrado, RA) values ("KEVERSON DOS SANTOS RODRIGUES","7891");
insert into registrados (nome_registrado, RA) values ("LAURA DE PAULA LORENA","12066");
insert into registrados (nome_registrado, RA) values ("LUANA GABRIELE DA SILVA PINTO","6189");
insert into registrados (nome_registrado, RA) values ("LUANA VIEIRA DE SOUZA VERISSIMO","11887");
insert into registrados (nome_registrado, RA) values ("MANUELI COUTINHO NUNES","17154");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE DE CASTRO SOUZA","12807");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE REZENDE FARIA DA SILVA","16593");
insert into registrados (nome_registrado, RA) values ("PEDRO LUCCA DE MORAES REIS","2095");
insert into registrados (nome_registrado, RA) values ("RAFAEL DE SA FONSECA ARAUJO","11927");
insert into registrados (nome_registrado, RA) values ("RHYAN BRANDAO DA SILVA","7150");
insert into registrados (nome_registrado, RA) values ("SARAH RAMOS MIRANDA DOS PASSOS","7293");
insert into registrados (nome_registrado, RA) values ("YARA GUEDES DA SILVA BATISTA","18751");
insert into registrados (nome_registrado, RA) values ("YGOR OLIVEIRA SANTOS","12790");
insert into registrados (nome_registrado, RA) values ("MYLENA LUGGERI DE ARAÚJO","6414");
insert into registrados (nome_registrado, RA) values ("SOFIA MOURA DE SOUZA SILVA","23521");
insert into registrados (nome_registrado, RA) values ("YASMIN COSTA XAVIER DA SILVA","18486");
insert into registrados (nome_registrado, RA) values ("GUSTAVO DOS SANTOS SIQUEIRA","8874");
insert into registrados (nome_registrado, RA) values ("ANA LARA DE SOUZA MELO","37124");
insert into registrados (nome_registrado, RA) values ("BRUNA CRISTINA DOS SANTOS","90");
insert into registrados (nome_registrado, RA) values ("CARLOS HENRIQUE SANTOS AMBROSIO","16044");
insert into registrados (nome_registrado, RA) values ("DANIEL ENRIQUE MENDES VENTURA","14518");
insert into registrados (nome_registrado, RA) values ("DAVI LUCAS LAUREANO DE OLIVEIRA","17891");
insert into registrados (nome_registrado, RA) values ("EDSON DAVID ALCANTARA NOVAIS","13558");
insert into registrados (nome_registrado, RA) values ("ERIK HENRIQUE CORDEIRO MAIA","3266");
insert into registrados (nome_registrado, RA) values ("EVELLYN VITORIA LEVAK DA SILVA","2907");
insert into registrados (nome_registrado, RA) values ("GUSTAVO HENRIQUE SOUZA DE PAULA","1462");
insert into registrados (nome_registrado, RA) values ("HENZO FRANCISCO DE JESUS","7540");
insert into registrados (nome_registrado, RA) values ("IARA SOUZA MACIEL","16793");
insert into registrados (nome_registrado, RA) values ("ISABEL LIA AMARAL DA SILVA","9889");
insert into registrados (nome_registrado, RA) values ("JHONATHA WILLYAN GLORIA SANTOS","16161");
insert into registrados (nome_registrado, RA) values ("JOÃO VICTOR LIMA VASQUES","5503");
insert into registrados (nome_registrado, RA) values ("JOSÉ EDUARDO FERNANDES SANTANA","12030");
insert into registrados (nome_registrado, RA) values ("LUIS GUSTAVO JESUINO FARIA FRANCO","7310");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA DO NASCIMENTO SILVA","16511");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA LEVAK DE OLIVEIRA","19242");
insert into registrados (nome_registrado, RA) values ("MARIA EDUARDA OLIVEIRA DE QUEIROZ","37418");
insert into registrados (nome_registrado, RA) values ("MARIA ELISA CARVALHO RAMOS DA SILVA","17557");
insert into registrados (nome_registrado, RA) values ("PEDRO HENRIQUE SOARES DOS SANTOS","12567");
insert into registrados (nome_registrado, RA) values ("SAMIRA CAROLINE CARVALHO","7184");
insert into registrados (nome_registrado, RA) values ("SUZANI VITORIA APARECIDA BUENO","27145");
insert into registrados (nome_registrado, RA) values ("THIAGO LEME DE PAULA","7248");
insert into registrados (nome_registrado, RA) values ("VITOR ROCHA DO NASCIMENTO","26880");
insert into registrados (nome_registrado, RA) values ("GHENIFER EMANUEL ASSUNÇÃO SANTOS","40168");
insert into registrados (nome_registrado, RA) values ("EDUARDO ALVES CAMILO","5142");
insert into registrados (nome_registrado, RA) values ("GABRIELLE SANTANA DOS SANTOS","13546");
